version: '3.7'

services:
  backend:
    build:
      context: "C:\\Users\\Coren\\TP1 DEVOPS\\Java2\\simpleapi\\simple-api-student-main\\simple-api-student-main"
    container_name: "my_student_api"
    networks:
      - app-network
    depends_on:
      - database

  database: 
    build:
      context: "C:\\Users\\Coren\\TP1 DEVOPS\\postgres"
    container_name: "my_postgres_container"
    networks:
      - app-network

  httpd:
    build:
      context: "C:\\Users\\Coren\\TP1 DEVOPS\\HTTP"
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
      - database

networks:
  app-network:
    
    

